/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TollRouteImport } from './routes/_toll'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TollTollIndexRouteImport } from './routes/_toll/toll/index'

const TollRoute = TollRouteImport.update({
  id: '/_toll',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TollTollIndexRoute = TollTollIndexRouteImport.update({
  id: '/toll/',
  path: '/toll/',
  getParentRoute: () => TollRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/toll/': typeof TollTollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/toll': typeof TollTollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_toll': typeof TollRouteWithChildren
  '/_toll/toll/': typeof TollTollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/toll/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/toll'
  id: '__root__' | '/' | '/_toll' | '/_toll/toll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TollRoute: typeof TollRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_toll': {
      id: '/_toll'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_toll/toll/': {
      id: '/_toll/toll/'
      path: '/toll'
      fullPath: '/toll/'
      preLoaderRoute: typeof TollTollIndexRouteImport
      parentRoute: typeof TollRoute
    }
  }
}

interface TollRouteChildren {
  TollTollIndexRoute: typeof TollTollIndexRoute
}

const TollRouteChildren: TollRouteChildren = {
  TollTollIndexRoute: TollTollIndexRoute,
}

const TollRouteWithChildren = TollRoute._addFileChildren(TollRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TollRoute: TollRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
